overrides:
  '@babel/helpers@<7.26.10': '>=7.26.10'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  cross-spawn@>=7.0.0 <7.0.5: '>=7.0.5'
  diff@<8.0.3: '>=8.0.3'
  dompurify@<2.4.2: '>=2.4.2'
  dompurify@<2.5.0: '>=2.5.0'
  dompurify@<2.5.4: '>=2.5.4'
  dompurify@<3.2.4: '>=3.2.4'
  esbuild@<=0.24.2: '>=0.25.0'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  jsonpath-plus@<10.2.0: '>=10.2.0'
  jsonpath-plus@<10.3.0: '>=10.3.0'
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  mermaid@<=10.9.2: '>=10.9.3'
  react-router@>=6.0.0 <6.30.2: '>=6.30.2'
  vite@<=5.4.19: '>=5.4.20'
  vite@>=4.5.3 <5.0.0: '>=5.4.21'
